version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - jenbutongit
  ignore:
  - dependency-name: webpack
    versions:
    - 5.26.0
    - 5.36.2
    - 5.37.0
    - 5.37.1
    - 5.38.1
    - 5.39.1
  - dependency-name: i18next
    versions:
    - 19.9.2
    - 20.2.2
    - 20.2.4
    - 20.3.1
  - dependency-name: prismjs
    versions:
    - 1.23.0
  - dependency-name: "@wdio/local-runner"
    versions:
    - 7.0.0
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.13.10
    - 7.13.15
    - 7.14.3
  - dependency-name: "@babel/register"
    versions:
    - 7.12.13
    - 7.13.14
    - 7.13.16
  - dependency-name: sass-loader
    versions:
    - 11.0.1
    - 11.1.0
    - 11.1.1
    - 12.0.0
  - dependency-name: copy-webpack-plugin
    versions:
    - 7.0.0
    - 8.1.1
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: node-sass
    versions:
    - 5.0.0

  - package-ecosystem: "npm"
    directory: "designer"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "runner"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "model"
    schedule:
      interval: "daily"
