version: 2.1
parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # This parameter is used to trigger the build-test workflow
  build-test:
    type: boolean
    default: false

  # If you need to force build all of the packages, set default: true
  force-build-all:
    type: boolean
    default: false

  # A parameter per package
  model:
    type: boolean
    default: false
  designer:
    type: boolean
    default: false
  runner:
    type: boolean
    default: false
  smoke-tests:
    type: boolean
    default: false
  test:
    type: boolean
    default: false
  docs:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node:12
  node-browsers:
    docker:
      - image: circleci/node:12.16-browsers
  python:
    docker:
      - image: circleci/python:2.7-jessie

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

  install-yarn:
    executor: node-browsers
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            # fallback to using the latest cache if no exact match is found
            - all-dependencies-{{ checksum "yarn.lock" }}
            - all-dependencies
      - run: yarn install
      - run: yarn rebuild node-sass only
      - save_cache:
          paths:
            - .yarn
            - model/dist
          key: all-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build-lint-test:
    parameters:
      package_name:
        type: string
      should_build:
        type: boolean

    executor: node-browsers
    working_directory: ~/project
    steps:
      - when:
          condition:
            or:
              # changes were made to this module, it needs to be rebuilt
              - << parameters.should_build >>

              # force flag
              - << pipeline.parameters.force-build-all >>

              # if the upstream dependencies (model) have changed, this package must be rebuilt.
              - and:
                  - equal: ["runner", << parameters.package_name >>]
                  - << pipeline.parameters.model >>
              - and:
                  - equal: ["designer", << parameters.package_name >>]
                  - << pipeline.parameters.model >>
          steps:
            - attach_workspace:
                at: ~/project

            - when:
                condition:
                  or:
                    - and:
                        - equal: ["runner", << parameters.package_name >>]
                        - or:
                            - not: << pipeline.parameters.model >>
                    - and:
                        - equal: ["designer", << parameters.package_name >>]
                        - not: << pipeline.parameters.model >>
                steps:
                  - run:
                      name: Build dependencies
                      command: |
                        yarn build:dependencies

            - run:
                name: Build
                command: |
                  yarn << parameters.package_name >> run build
            - run:
                name: Test
                command: yarn << parameters.package_name >> run test-cov
            - store_test_results:
                path: << parameters.package_name >>/test-results
            - store_artifacts:
                path: << parameters.package_name >>/test-coverage
            - persist_to_workspace:
                root: ~/project
                paths:
                  - .
      - run:
          name: Changes made to << parameters.package_name >> - << parameters.should_build >>
          command: |
            if [ ! '<< parameters.should_build >>' = 'true' ]; then
              circleci-agent step halt
            fi

workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

  build-test:
    when: << pipeline.parameters.build-test >>
    jobs:
      - install-yarn
      - build-lint-test:
          name: model-build-lint-test
          package_name: model
          should_build: << pipeline.parameters.model >>
          requires:
            - install-yarn

      - build-lint-test:
          name: runner-build-lint-test
          package_name: runner
          should_build: << pipeline.parameters.runner >>
          requires:
            - model-build-lint-test

      - build-lint-test:
          name: designer-build-lint-test
          package_name: designer
          should_build: << pipeline.parameters.designer >>
          requires:
            - model-build-lint-test
