version: 2.1
parameters:
  # This parameter is used to trigger the build-test workflow
  build-test:
    type: boolean
    default: true

  # If you need to force build all of the packages, set default: true
  force-build-all:
    type: boolean
    default: true

  # A parameter per package
  model:
    type: boolean
    default: false
  designer:
    type: boolean
    default: false
  runner:
    type: boolean
    default: false
  smoke-tests:
    type: boolean
    default: false
  test:
    type: boolean
    default: false
  docs:
    type: boolean
    default: false

executors:
  node-browsers:
    docker:
      - image: cimg/node:12.19.1-browsers

jobs:
  install-yarn-lint:
    executor: node-browsers
    working_directory: ~/project
    steps:
      - checkout
      - run: yarn install
      - run: yarn rebuild node-sass only
      - run:
          name: Lint
          command: |
            yarn lint

      - run: yarn build:dependencies
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build-test:
    parameters:
      package_name:
        type: string
      should_build:
        type: boolean

    executor: node-browsers
    working_directory: ~/project
    steps:
      - when:
          condition:
            or:
              # changes were made to this module, it needs to be rebuilt
              - << parameters.should_build >>

              # force flag
              - << pipeline.parameters.force-build-all >>

          steps:
            - attach_workspace:
                at: ~/project

            - when:
                condition:
                  not: << pipeline.parameters.model >>
                steps:
                  - run:
                      name: Build
                      command: |
                        yarn << parameters.package_name >> run build

            - run:
                name: Build
                command: |
                  yarn << parameters.package_name >> run build
            - run:
                name: Test
                command: yarn << parameters.package_name >> run test-cov

          post-steps:
            - run:
                command: Upload test results
            - store_test_results:
                path: << parameters.package_name >>/test-results
            - store_artifacts:
                path: << parameters.package_name >>/test-coverage

      - run:
          name: Changes made to << parameters.package_name >> - << parameters.should_build >>
          command: |
            if [ ! '<< parameters.should_build >>' = 'true' ]; then
              circleci-agent step halt
            fi

workflows:
  version: 2

  build-test:
    when: << pipeline.parameters.build-test >>
    jobs:
      - install-yarn-lint
      - build-test:
          name: model-build-test
          package_name: model
          should_build: << pipeline.parameters.model >>
          requires:
            - install-yarn-lint

      - build-test:
          name: runner-build-test
          package_name: runner
          should_build: << pipeline.parameters.runner >>
          requires:
            - install-yarn-lint

      - build-test:
          name: designer-build-test
          package_name: designer
          should_build: << pipeline.parameters.designer >>
          requires:
            - install-yarn-lint
