---
apiVersion: v1
kind: Service
metadata:
  name: {{ .NAME }}
  labels:
    project: stp
spec:
  selector:
    app: {{ .NAME }}
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: {{ .PORT }}
...