name: Deploy Development Environment

on:
  workflow_dispatch:
    inputs:
      app:
        description: "Name of the app to deploy to heroku"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy development ${{ github.event.inputs.app }}
    steps:
      - name: Works
        run: echo "Works ${{ github.event.inputs.app }}"
      # - uses: actions/checkout@v2
      # - name: Login to Heroku Container registry
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_DEV_API_KEY }}
      #   run: heroku container:login

      # - name: Pull latest ${{ github.event.inputs.app }} image
      #   run: docker pull ghcr.io/xgovformbuilder/digital-form-builder-${{ github.event.inputs.app }}:latest

      # - name: Tag Image
      #   run: docker tag ghcr.io/xgovformbuilder/digital-form-builder-${{ github.event.inputs.app }}:latest registry.heroku.com/digital-form-builder-${{ github.event.inputs.app }}/web

      # - name: Push to Heroku Registry
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_DEV_API_KEY }}
      #   run: docker push registry.heroku.com/digital-form-builder-${{ github.event.inputs.app }}/web

      # - name: Release
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_DEV_API_KEY }}
      #   run: heroku container:release -a digital-form-builder-${{ github.event.inputs.app }} web
