# This is a reusable workflow unit which can be used to deploy to heroku.
# To deploy, add the following to your workflow
#deploy:
#  needs: [calculate-version, assign-semver, build-and-publish-images]
#  uses: ./.github/workflows/deploy-development.yml
#  secrets: inherit
#  with:
#    repository: # heroku repository to push to
#    app: runner
#    tag: ${{ needs.assign-semver.outputs.SEMVER }}

name: Deploy Development Environment

on:
  workflow_dispatch:
    inputs:
      app:
        description: "Name of the app to deploy to heroku"
        required: true
      tag:
        description: "Tag to use for heroku deployments"
        required: true
      repository:
        required: true
        description: "The heroku repository to push to"
  workflow_call:
    inputs:
      app:
        description: "Name of the app to deploy to heroku"
        required: true
        type: string
      tag:
        description: "Tag to use for heroku deployments"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy development ${{ inputs.app }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_DEV_API_KEY }}
        run: npx --yes heroku container:login

      - name: Pull latest ${{ inputs.app }} image
        run: docker pull ghcr.io/xgovformbuilder/digital-form-builder-${{ inputs.app }}:${{ inputs.tag }}

      - name: Tag Image
        run: docker tag ghcr.io/xgovformbuilder/digital-form-builder-${{ inputs.app }}:${{ inputs.tag }} ${{ inputs.repository }}

      - name: Push to Heroku Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_DEV_API_KEY }}
        run: docker push ${{ inputs.repository }}

      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_DEV_API_KEY }}
        run: npx --yes heroku container:release -a digital-form-builder-${{ inputs.app }} web
