name: Dispatch to external repositories

on:
  push:
    branches: chore/notify-ho
    tags:
      - '*'

jobs:
  parse:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          JSON=$(cat .github/workflows/notifications.json)
          echo ::set-output name=matrix::${JSON//'%'/'%25'}
  notify:
    runs-on: ubuntu-latest
    needs: parse
    strategy:
      matrix: ${{fromJson(needs.parse.outputs.matrix)}}
    steps:
    - uses: octokit/request-action@v2.x
      with:
        route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
        owner: ${{matrix.owner}}
        repo: ${{matrix.repo}}
        workflow_id: ${{matrix.workflow_id}}
        ref: ${{matrix.ref}}
        inputs: '{ "sha": "${{github.sha}}", "tag": "${{env.TAG}}" }'
      env:
        GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
        TAG: ${{contains(github.ref, /refs/tags/) && github.ref}}