name: Dispatch to external repositories

on:
  push:
    tags:
      - '*'
    branches:
      - 'chore/readjust-semver'
jobs:
  parse:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      tag:  ${{ steps.set-matrix.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          JSON=$(cat .github/workflows/notifications.json)
          TAG_REF=${{(contains(github.ref, 'refs/tags/') && github.ref) || ''}}
          echo ::set-output name=matrix::${JSON//'%'/'%25'}
          echo ::set-output name=tag::${TAG_REF/refs\/tags\/}
  notify:
    runs-on: ubuntu-latest
    needs: parse
    strategy:
      matrix: ${{fromJson(needs.parse.outputs.matrix)}}
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - run: echo "${{ github.event.inputs.tag }}"
#    - uses: octokit/request-action@v2.x
#      with:
#        route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
#        owner: ${{matrix.owner}}
#        repo: ${{matrix.repo}}
#        workflow_id: ${{matrix.workflow_id}}
#        ref: ${{matrix.ref}}
#        inputs: '{ "sha": "${{github.sha}}", "tag": "${{needs.parse.outputs.tag}}", "branch": "${{steps.extract_branch.outputs.branch}}" }'
#      env:
#        GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
