name: Smoke Tests Nightly - Heroku
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: xgovformbuilder/digital-form-builder-legacy-smoke-tests@main
        with:
          script: 'heroku'

      - uses: actions/upload-artifact@v2
        if: ${{ success() || failure() }}
        with:
          name: smoke-tests-nightly-heroku
          path: smoke-tests-nightly-heroku.tar
          retention-days: 14

      - uses: rtCamp/action-slack-notify@v2
        if: ${{failure()}}
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR: '#990000'
          SLACK_MESSAGE: 'Nightly - Smoke Test, job for heroku failed'
          SLACK_TITLE: Smoke Test failure
          SLACK_USERNAME: forms-nightly-bot
          SLACK_ICON: https://a.slack-edge.com/80588/img/services/outgoing-webhook_128.png
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - uses: rtCamp/action-slack-notify@v2
        if: ${{failure()}}
        env:
          SLACK_CHANNEL: ${{ secrets.CYB_SLACK_CHANNEL }}
          SLACK_COLOR: '#990000'
          SLACK_MESSAGE: 'Nightly - Smoke Test, job for heroku failed'
          SLACK_TITLE: Smoke Test failure
          SLACK_USERNAME: forms-nightly-bot
          SLACK_ICON: https://a.slack-edge.com/80588/img/services/outgoing-webhook_128.png
          SLACK_WEBHOOK: ${{ secrets.CYB_SLACK_WEBHOOK }}

